name: CI
on: [push]
jobs:
  lighthouseci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm install && npm install -g @lhci/cli
      - run: lhci autorun